feat UserCard
stevensblueprint/blueprint_admin pull request #22
Opened 2024-03-28 23:38 UTC by mpate154

added userCard

2024-04-02 16:42 UTC, miguel-merlin requested changes
@mpate154 Solid PR, please make the changes I highlighted in the review. Keep it up!

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +          <ModalBody>
@mpate154 I don't think creating a Modal body for each of the fields is the correct approach. You can instead try
```
          <ModalBody>
            <p>Name:</p>
            <Editable defaultValue={name} onSubmit={(value) => setName(value)}>
              <EditablePreview />
              <EditableInput />
            </Editable>
            {/* Repeat for email, status, and title with their respective states */}
          </ModalBody>
```

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
@mpate154 You also have to create a useState for all the inputs of the form. For example:
```
const [name, setName] = useState(userName);
```
This will tell react to rerender the input form whenever the user writes something to the input box

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
>    return (
Since we need to make an API call when the button is closed I would also recommend adding a ```saveChanges``` function that handles the API call. For now you can leave it as  
```
 const saveChanges = () => {
    onClose(); // Close modal after saving
  };
``` 
Remeber to change ```<Button variant="ghost" onClick={saveChanges}>Save</Button>```

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +import { useDisclosure } from "@chakra-ui/react";
You are importing multiple times from ```@chakra-ui/react``` you can include all your ```@chakra-ui/react``` imports into a single one

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +import { useState } from "react"; //for the save button that hasnt' been implemented
You are importing multiple times from ```react``` you can include all your ```react```  imports into a single one

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +              <EditablePreview /*need?*/ />
Yes this is needed

2024-04-02 16:42 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +            <Editable>
When the user enters input, you need to tell react to change the state. You have to include
```
<Editable defaultValue={name} onSubmit={(value) => setName(value)}>
```

Same for all other ```<Editable/>```

2024-04-08 21:21 UTC, miguel-merlin commented
@mpate154 Do you have any questions on the comments I've made to your pull request?

2024-04-09 01:04 UTC, mpate154 commented
Hi!

I'll take a look right now and let you know,
Thanks!
Maya
________________________________
From: Miguel Merlin ***@***.***>
Sent: Monday, April 8, 2024 5:21 PM
To: stevensblueprint/blueprint_admin ***@***.***>
Cc: Maya Patel ***@***.***>; Mention ***@***.***>
Subject: Re: [stevensblueprint/blueprint_admin] feat UserCard (PR #22)

CAUTION: This email originated from outside the organization. Please do not click links or open attachments unless you recognize the sender and know the content is safe.


@mpate154<https://github.com/mpate154> Do you have any questions on the comments I've made to your pull request?

—
Reply to this email directly, view it on GitHub<https://github.com/stevensblueprint/blueprint_admin/pull/22#issuecomment-2043663070>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDHPH4FLOB6DICBSSCCTGD3Y4MC5PAVCNFSM6AAAAABFNUQDL2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBTGY3DGMBXGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-04-09 01:46 UTC, mpate154 commented
For the const [userName, setName] = useState(userName); and the others, is it supposed to be inside the card? It's also giving me an error because its 'duplicate identifer 'username''.

function UserCard({
  buttonText,
  userName,
  email,
  status,
  title,
}: UserCardProps): JSX.Element {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [userName, setName] = useState(userName); //does this go here?
  const [email, setEmail] = useState(email);
  const [status, setStatus] = useState(status);
  const [title, setTitle] = useState(title);
Thank you!
Maya Patel
________________________________
From: Miguel Merlin ***@***.***>
Sent: Tuesday, April 2, 2024 12:42 PM
To: stevensblueprint/blueprint_admin ***@***.***>
Cc: Maya Patel ***@***.***>; Mention ***@***.***>
Subject: Re: [stevensblueprint/blueprint_admin] feat UserCard (PR #22)

CAUTION: This email originated from outside the organization. Please do not click links or open attachments unless you recognize the sender and know the content is safe.


@miguel-merlin requested changes on this pull request.

@mpate154<https://github.com/mpate154> Solid PR, please make the changes I highlighted in the review. Keep it up!

________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548210085>:

>    return (
-    <div>
-    </div>
-  )
+    <>
+      <Button onClick={onOpen}>{buttonText}</Button>
+
+      <Modal isOpen={isOpen} onClose={onClose}>
+        <ModalOverlay />
+        <ModalContent>
+          <ModalHeader>{userName} Information</ModalHeader>
+          <ModalCloseButton />
+
+          <ModalBody>


@mpate154<https://github.com/mpate154> I don't think creating a Modal body for each of the fields is the correct approach. You can instead try

          <ModalBody>
            <p>Name:</p>
            <Editable defaultValue={name} onSubmit={(value) => setName(value)}>
              <EditablePreview />
              <EditableInput />
            </Editable>
            {/* Repeat for email, status, and title with their respective states */}
          </ModalBody>


________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548212339>:

> +interface UserCardProps {
+  buttonText: string;
+  userName: string;
+  email: string;
+  status: string;
+  title: string;
+}
+
+function UserCard({
+  buttonText,
+  userName,
+  email,
+  status,
+  title,
+}: UserCardProps): JSX.Element {
+  const { isOpen, onOpen, onClose } = useDisclosure();


@mpate154<https://github.com/mpate154> You also have to create a useState for all the inputs of the form. For example:

const [name, setName] = useState(userName);


This will tell react to rerender the input form whenever the user writes something to the input box

________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548215352>:

> +interface UserCardProps {
+  buttonText: string;
+  userName: string;
+  email: string;
+  status: string;
+  title: string;
+}
+
+function UserCard({
+  buttonText,
+  userName,
+  email,
+  status,
+  title,
+}: UserCardProps): JSX.Element {
+  const { isOpen, onOpen, onClose } = useDisclosure();
   return (


Since we need to make an API call when the button is closed I would also recommend adding a saveChanges function that handles the API call. For now you can leave it as

 const saveChanges = () => {
    onClose(); // Close modal after saving
  };


Remeber to change <Button variant="ghost" onClick={saveChanges}>Save</Button>

________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548218121>:

> @@ -1,8 +1,96 @@
-function UserCard (): JSX.Element {
+import { useState } from "react"; //for the save button that hasnt' been implemented
+import React from "react";
+import sampleUserData from "../sample_data.json";
+import { useDisclosure } from ***@***.***/react";


You are importing multiple times from @chakra-ui/react you can include all your @chakra-ui/react imports into a single one

________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548219318>:

> @@ -1,8 +1,96 @@
-function UserCard (): JSX.Element {
+import { useState } from "react"; //for the save button that hasnt' been implemented


You are importing multiple times from react you can include all your react imports into a single one

________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548220895>:

> -    </div>
-  )
+    <>
+      <Button onClick={onOpen}>{buttonText}</Button>
+
+      <Modal isOpen={isOpen} onClose={onClose}>
+        <ModalOverlay />
+        <ModalContent>
+          <ModalHeader>{userName} Information</ModalHeader>
+          <ModalCloseButton />
+
+          <ModalBody>
+            Name:
+            <Editable>
+              {userName}
+              <EditablePreview /*need?*/ />


Yes this is needed

________________________________

In src/components/UserCard.tsx<https://github.com/stevensblueprint/blueprint_admin/pull/22#discussion_r1548224854>:

>    return (
-    <div>
-    </div>
-  )
+    <>
+      <Button onClick={onOpen}>{buttonText}</Button>
+
+      <Modal isOpen={isOpen} onClose={onClose}>
+        <ModalOverlay />
+        <ModalContent>
+          <ModalHeader>{userName} Information</ModalHeader>
+          <ModalCloseButton />
+
+          <ModalBody>
+            Name:
+            <Editable>


When the user enters input, you need to tell react to change the state. You have to include

<Editable defaultValue={name} onSubmit={(value) => setName(value)}>


Same for all other <Editable/>

—
Reply to this email directly, view it on GitHub<https://github.com/stevensblueprint/blueprint_admin/pull/22#pullrequestreview-1974357854>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDHPH4GJJUBKC6GCLPJULQDY3LNX7AVCNFSM6AAAAABFNUQDL2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNZUGM2TOOBVGQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-04-17 23:21 UTC, miguel-merlin requested changes

2024-04-17 23:21 UTC, miguel-merlin commented on package.json
> +    "mongodb": "^6.5.0",
Why did you install the mongodb driver?
You can undo by running
```
npm uninstall mongodb
```

2024-04-17 23:21 UTC, miguel-merlin commented on src/app/App.tsx
> +        <Route path="/" element={<HomePage />} />
We usually want to keep the pull request atomic, meaning the PR only focuses on one change, usually styling changes like this have to be done in another PR

2024-04-17 23:21 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +import { setTokenSourceMapRange } from "typescript";
What is this for?

2024-04-17 23:21 UTC, miguel-merlin commented on src/components/UserCard.tsx
> +          <ModalHeader>{userName} Information</ModalHeader>
nit: 
```
{userName}'s Information
```

2025-02-01 21:59 UTC, closed without merging