Created the AddUser button on the Dashboard page
stevensblueprint/blueprint_admin pull request #23
Opened 2024-04-02 15:47 UTC by Lucasha11

Created the "Add User" button on the dashboard page. When request is successful, alert is displayed on screen. "Add User" has two inputs "Email" and "Roles."

2024-04-02 16:55 UTC, miguel-merlin requested changes
Good job! Please address the comments I've made. Keep it up!

2024-04-02 16:55 UTC, miguel-merlin commented on README.md
> +git
What is this?

2024-04-02 16:55 UTC, miguel-merlin commented on src/components/CreateUserButton.tsx
> +
A more conventional approach to dealing with form data would be 
```
const [formData, setFormData] = useState({ email: '', roles: '' });
``` 
and to handle the input of the user

```
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };
```

2024-04-02 16:55 UTC, miguel-merlin commented on src/components/CreateUserButton.tsx
> +  const handleSubmit: () => void = () => {
Usually API calls have to by in a try-catch block: You could try:
```
  const handleSubmit = async () => {
    console.log('Form submitted', formData);
    try {
      const apiState = true;
      if (!apiState) throw new Error('API call failed');
      setDisplaySuccess(true);
      onClose();
    } catch (error) {
      setDisplayError(true);
    }
  };
```

2024-04-02 16:55 UTC, miguel-merlin commented on src/components/CreateUserButton.tsx
> +            {displayError ? <Alert status='error'> <AlertIcon /> Request failed </Alert> : <></>}
Try:
```
            {displayError && (
              <Alert status="error">
                <AlertIcon />
                Request failed
              </Alert>
            )}
```

2024-04-02 16:55 UTC, miguel-merlin commented on src/components/CreateUserButton.tsx
> +              <Input ref={initialRef} placeholder='Email' />
Try:
```
              <Input
                name="email"
                placeholder="Email"
                ref={initialRef}
                onChange={handleChange}
                value={formData.email}
              />
```

2024-04-02 16:55 UTC, miguel-merlin commented on src/components/CreateUserButton.tsx
> +              <Input placeholder='Roles' />
Try:
```
              <Input
                name="roles"
                placeholder="Roles"
                onChange={handleChange}
                value={formData.roles}
              />
```

2024-04-02 16:55 UTC, miguel-merlin commented on src/components/CreateUserButton.tsx
> +            <Button onClick={onClose}>Cancel</Button>
```
<Button colorScheme="blue" mr={3} onClick={handleSubmit}>
```
To handle submission

2024-04-02 16:55 UTC, miguel-merlin commented on src/pages/DashboardPage.tsx
> +    <HStack height="100vh" spacing="0">
I think using ```<VStack>``` could make layout of the page easier. It helps you stack components on top of each other.

2024-04-02 16:55 UTC, miguel-merlin commented on src/pages/DashboardPage.tsx
> +      {displaySuccess ? <Box pt={740} position="relative" h="100vh" w='20%'><Alert status='success'> <AlertIcon /> Request success </Alert> </Box> : <></>}
Try instead:
```
      {displaySuccess && (
        <Alert status="success">
          <AlertIcon />
          Request success
        </Alert>
      )}
```

2024-04-02 16:55 UTC, miguel-merlin commented on src/pages/DashboardPage.tsx
> +      <Container><CreateUserButton displaySuccess={displaySuccess} setDisplaySuccess={setDisplaySuccess} />
```displaySuccess``` is not needed anymore. By removing displaySuccess from the props of CreateUserButton, the component becomes more encapsulated and focused on its specific task. Since you pass the setter setDisplaySuccess, you don't need the value of displaySuccess in the Component

2024-04-08 22:10 UTC, miguel-merlin commented
@Lucasha11 This one was a tricky one! You cannot have async functions onSubmit. To handle API calls onSubmit, you need to write your submit handler in such a way that the promise is handled internally.  Please keep working on the comments I provided; let me know if you have any questions. Please, when requesting the review, resolve all the comments you have addressed.

2024-04-09 21:45 UTC, Lucasha11 commented
Miguel resolved my async issue. This PR should contain the completed "Add User Button."

2024-04-10 04:09 UTC, miguel-merlin approved these changes
Great job!

2024-04-10 04:09 UTC, merged