feat: added sidebar (#1)
stevensblueprint/blueprint_admin pull request #9
Opened 2024-02-17 01:09 UTC by ZhangTerrence

I added the sidebar but there are some features I wasn't able to add:

- No icons in the buttons, apparently ChakraUI requires you to install a separate node package to use its icons. Also, ChakraUI's icon library is pretty small. https://chakra-ui.com/docs/components/icon/usage
- I left the image srcs empty for now
- I don't know how it should look for mobile so right now its not mobile responsive

Also I put the Sidebar components in a newly created components directory. I wasn't sure where to put it for this project it's there for now.

2024-02-22 19:55 UTC, miguel-merlin requested changes

2024-02-22 19:55 UTC, miguel-merlin commented on src/components/Sidebar.tsx
> +              <Image src='' alt="Blueprint Logo" boxSize="100px"></Image>
@ZhangTerrence I just added the logos in your branch ```feat/sidebar``` under ```src/assets/images```. Can you update the src

2024-02-22 19:55 UTC, miguel-merlin commented on src/components/Sidebar.tsx
> +            <HStack padding="16px">
@ZhangTerrence We don't really need this for now. Since authentication is managed by Authelia for now we won't support changing any information of the logged in user

2024-02-22 19:55 UTC, miguel-merlin commented on src/components/Sidebar.tsx
> +function Sidebar (): JSX.Element {
@ZhangTerrence In ```main``` I just pushed new changes where I use React-Router-Dom to handle routing. Can you add this to the ```HomePage.tsx``` and change the routing of the Sidebar component (When clicked on Home go to HomePage, when clicked on Blog go to BlogPage etc).

2024-02-22 21:07 UTC, ZhangTerrence commented
I updated the image srcs, added routing functionality to the buttons, and moved Sidebar to HomePage. As for the icons, I was able to get some free svgs so I created custom icons which I temporarily put in the icons directory.

2024-02-22 21:09 UTC, miguel-merlin commented
You're crazy. Thanks

2024-02-27 15:25 UTC, miguel-merlin approved these changes
Thanks for your work!

2024-02-27 15:25 UTC, merged